# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/majumder/bitsandbytes_kernel_samples/tests

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/majumder/bitsandbytes_kernel_samples/tests

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/majumder/bitsandbytes_kernel_samples/tests/CMakeFiles /home/majumder/bitsandbytes_kernel_samples/tests//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/majumder/bitsandbytes_kernel_samples/tests/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bitsandbytes

# Build rule for target.
bitsandbytes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bitsandbytes
.PHONY : bitsandbytes

# fast build rule for target.
bitsandbytes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/build
.PHONY : bitsandbytes/fast

sycl/common.o: sycl/common.cpp.o
.PHONY : sycl/common.o

# target to build an object file
sycl/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/common.cpp.o
.PHONY : sycl/common.cpp.o

sycl/common.i: sycl/common.cpp.i
.PHONY : sycl/common.i

# target to preprocess a source file
sycl/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/common.cpp.i
.PHONY : sycl/common.cpp.i

sycl/common.s: sycl/common.cpp.s
.PHONY : sycl/common.s

# target to generate assembly for a file
sycl/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/common.cpp.s
.PHONY : sycl/common.cpp.s

sycl/cpu_ops.o: sycl/cpu_ops.cpp.o
.PHONY : sycl/cpu_ops.o

# target to build an object file
sycl/cpu_ops.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/cpu_ops.cpp.o
.PHONY : sycl/cpu_ops.cpp.o

sycl/cpu_ops.i: sycl/cpu_ops.cpp.i
.PHONY : sycl/cpu_ops.i

# target to preprocess a source file
sycl/cpu_ops.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/cpu_ops.cpp.i
.PHONY : sycl/cpu_ops.cpp.i

sycl/cpu_ops.s: sycl/cpu_ops.cpp.s
.PHONY : sycl/cpu_ops.s

# target to generate assembly for a file
sycl/cpu_ops.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/cpu_ops.cpp.s
.PHONY : sycl/cpu_ops.cpp.s

sycl/pythonInterface.o: sycl/pythonInterface.cpp.o
.PHONY : sycl/pythonInterface.o

# target to build an object file
sycl/pythonInterface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/pythonInterface.cpp.o
.PHONY : sycl/pythonInterface.cpp.o

sycl/pythonInterface.i: sycl/pythonInterface.cpp.i
.PHONY : sycl/pythonInterface.i

# target to preprocess a source file
sycl/pythonInterface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/pythonInterface.cpp.i
.PHONY : sycl/pythonInterface.cpp.i

sycl/pythonInterface.s: sycl/pythonInterface.cpp.s
.PHONY : sycl/pythonInterface.s

# target to generate assembly for a file
sycl/pythonInterface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/pythonInterface.cpp.s
.PHONY : sycl/pythonInterface.cpp.s

sycl/sycl_code/kernel_quant.o: sycl/sycl_code/kernel_quant.cpp.o
.PHONY : sycl/sycl_code/kernel_quant.o

# target to build an object file
sycl/sycl_code/kernel_quant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/sycl_code/kernel_quant.cpp.o
.PHONY : sycl/sycl_code/kernel_quant.cpp.o

sycl/sycl_code/kernel_quant.i: sycl/sycl_code/kernel_quant.cpp.i
.PHONY : sycl/sycl_code/kernel_quant.i

# target to preprocess a source file
sycl/sycl_code/kernel_quant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/sycl_code/kernel_quant.cpp.i
.PHONY : sycl/sycl_code/kernel_quant.cpp.i

sycl/sycl_code/kernel_quant.s: sycl/sycl_code/kernel_quant.cpp.s
.PHONY : sycl/sycl_code/kernel_quant.s

# target to generate assembly for a file
sycl/sycl_code/kernel_quant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/sycl_code/kernel_quant.cpp.s
.PHONY : sycl/sycl_code/kernel_quant.cpp.s

sycl/sycl_code/op_quant.o: sycl/sycl_code/op_quant.cpp.o
.PHONY : sycl/sycl_code/op_quant.o

# target to build an object file
sycl/sycl_code/op_quant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/sycl_code/op_quant.cpp.o
.PHONY : sycl/sycl_code/op_quant.cpp.o

sycl/sycl_code/op_quant.i: sycl/sycl_code/op_quant.cpp.i
.PHONY : sycl/sycl_code/op_quant.i

# target to preprocess a source file
sycl/sycl_code/op_quant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/sycl_code/op_quant.cpp.i
.PHONY : sycl/sycl_code/op_quant.cpp.i

sycl/sycl_code/op_quant.s: sycl/sycl_code/op_quant.cpp.s
.PHONY : sycl/sycl_code/op_quant.s

# target to generate assembly for a file
sycl/sycl_code/op_quant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bitsandbytes.dir/build.make CMakeFiles/bitsandbytes.dir/sycl/sycl_code/op_quant.cpp.s
.PHONY : sycl/sycl_code/op_quant.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bitsandbytes"
	@echo "... sycl/common.o"
	@echo "... sycl/common.i"
	@echo "... sycl/common.s"
	@echo "... sycl/cpu_ops.o"
	@echo "... sycl/cpu_ops.i"
	@echo "... sycl/cpu_ops.s"
	@echo "... sycl/pythonInterface.o"
	@echo "... sycl/pythonInterface.i"
	@echo "... sycl/pythonInterface.s"
	@echo "... sycl/sycl_code/kernel_quant.o"
	@echo "... sycl/sycl_code/kernel_quant.i"
	@echo "... sycl/sycl_code/kernel_quant.s"
	@echo "... sycl/sycl_code/op_quant.o"
	@echo "... sycl/sycl_code/op_quant.i"
	@echo "... sycl/sycl_code/op_quant.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

